baseURL = "http://example.org/"
languageCode = "en"
defaultContentLanguage = "en"
title = "My New Hugo Site"
publishDir = "public"
theme = "dream"
[params]
  author = "Pitágoras Alves"
  motto = "<my motto>"
  description = "<my description>"
  avatar = "<my_avatar>"
  
  email = "alves.pitagoras@gmail.com"
  github = "github.com/pentalpha"
  linkedin = ""
  codepen = ""
  stackoverflow = ""
  googleAnalytics = ""
  disqusShortname = ""
  copyright = ""
